name: 'Example'

on: [push]

jobs:
  report:

    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: ./example

    # https://github.com/actions/cache/blob/master/examples.md#php---composer
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Composer Install
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --quiet --no-suggest
      working-directory: ./example
    
    - name: Type Check
      run: composer check -- --report=report.json --stats
      working-directory: ./example

    - name: Report Failures
      if: always()
      uses: beaucollins/psalm-annotations-action@master
      with:
        report_path: ./example/report.json
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
