name: 'Example'

on: [push]

jobs:
  report:

    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: ./example

    - name: Composer Install
      run: composer install
      working-directory: ./example
    
    - name: Type Check
      run: composer check -- --report=report.json --stats
      working-directory: ./example

    - name: Report Failures
      if: failure()
      uses: beaucollins/psalm-annotations-action@master
      with:
        report_path: ./example/report.json
